WIP: feat: preload server page
blocklet/blocklet-launcher pull request #47
Opened 2022-01-17 04:40 UTC by kirakiray

2022-01-17 09:25 UTC, wangshijun requested changes
https://github.com/blocklet/blocklet-server-launcher/pull/350#discussion_r785770131

2022-01-17 10:13 UTC, wangshijun requested changes

2022-01-17 10:13 UTC, wangshijun commented on src/pages/launch.js
> +      }, 3000);
这个三秒可能太短了，先设置成 5 秒吧

2022-01-17 13:11 UTC, kirakiray commented on src/pages/launch.js
> +      }, 3000);
更新为5秒

2022-01-17 23:07 UTC, wangshijun requested changes

2022-01-17 23:07 UTC, wangshijun commented on src/libs/utils.js
> +const preloadPage = (url, time = 5000) =>
time --> timeout

2022-01-17 23:07 UTC, wangshijun commented on src/pages/launch.js
> +  const getLaunchNodeUrl = (node) => {
getLaunchNodeUrl --> getNodeUrl

2022-01-17 23:07 UTC, wangshijun commented on src/pages/launch.js
> +  }, [abtnodes, selectedNode, blockletMetaUrl]);
这个逻辑如果存在，应该不限于 3 个？可以选中 node 时立即缓存，不论有多少个，然后点击启动时再缓存，如果已经缓存，速度会快很多。

2022-01-17 23:07 UTC, wangshijun commented on src/pages/launch.js
> +  const toNode = (node) => {
toNode --> openNode

2022-01-17 23:07 UTC, wangshijun commented on src/libs/utils.js
> +    preloadFrame.id = 'server-preload-page';
这个 id 是重复的？如果没必要可以删掉？

2022-01-18 01:58 UTC, kirakiray commented on src/libs/utils.js
> +    preloadFrame.id = 'server-preload-page';
标识 iframe 用途，当iframe 没删除可以快速定位；已改为 attribute 'preload-page'

2022-01-18 01:59 UTC, kirakiray commented on src/pages/launch.js
> +  }, [abtnodes, selectedNode, blockletMetaUrl]);
已更新为选中节点改变立刻缓存节点；放开点击后的不缓存逻辑；

2022-01-18 02:08 UTC, wangshijun approved these changes

2022-01-18 02:08 UTC, merged