WIP: feat: can add blocklet server custom
blocklet/blocklet-launcher pull request #62
Opened 2022-01-26 08:46 UTC by kirakiray

https://github.com/blocklet/blocklet-server-launcher/issues/339

![image](https://user-images.githubusercontent.com/5945154/151131142-c100f61d-2efb-43b2-9a83-e73f5d72cc9a.png)

![image](https://user-images.githubusercontent.com/5945154/151131171-04b62018-257c-463a-a225-4b37fed9ea55.png)

2022-01-26 10:16 UTC, wangshijun requested changes

2022-01-26 10:16 UTC, wangshijun commented on CHANGELOG.md
> +feat: can add blocklet server custom
我印象中 change log 里面的 item 是 markdown 的 list 语法？

2022-01-26 10:16 UTC, wangshijun commented on src/components/split-button.js
> +  menulist: PropTypes.array,
menulist --> menuItems

2022-01-26 10:16 UTC, wangshijun commented on src/pages/launch.js
> +            isAdd: 1,
isAdd --> source: 'register'

2022-01-27 04:14 UTC, kirakiray commented on src/pages/index.js
> +    const localServers = localStorage.localServers ? JSON.parse(localStorage.localServers) : [];
已将相关 state 移到 instances 文件

2022-01-27 07:29 UTC, polunzh commented on src/components/guide-gallery.js
> +  const [currentid, setCurrentid] = useState(0);
currentid 应该使用驼峰命名

2022-01-27 08:08 UTC, wangshijun requested changes

2022-01-27 08:08 UTC, wangshijun commented on src/components/instance/item.js
> +  .local_mark {
local_mark 下划线和 close-btn 风格混用，改成一致的吧，这种问题之前提过

2022-01-27 08:21 UTC, wangshijun approved these changes
let's ship it

2022-01-27 09:45 UTC, merged